version: '3'

services:
  backend:
    build:
      context: ./api
      dockerfile: ./dockerfile
    image: "shifta/api"
    ports:
      - "4000:4000"
  frontend:
    build:
      context: ./client
      dockerfile: ./dockerfile
    image: "shifta/client"
    ports:
      - "3000:3000"
